def Students():
    students=[
        {
            'id':1,
            'name':'anoop',
            'place':'calicut',
            'mobile':9876541320,
            'email':'anoop@gmail.com',
            'joindate':'06/10/2018'
        },
        {
            'id':2,
            'name':'anil',
            'place':'calicut',
            'mobile':8876541320,
            'email':'anil@gmail.com',
            'joindate':'03/08/2018'
        },
        {
            'id':3,
            'name':'akhil',
            'place':'kochi',
            'mobile':7876542320,
            'email':'akhil@gmail.com',
            'joindate':'25/12/2018'
        },
        {
            'id':4,
            'name':'bibin',
            'place':'thrissur',
            'mobile':7876541327,
            'email':'bibin24@gmail.com',
            'joindate':'23/03/2016'
        },
        {
            'id':4,
            'name':'binil',
            'place':'thrissur',
            'mobile':9976541323,
            'email':'binil54@gmail.com',
            'joindate':'26/09/2018'
        },
        {
            'id':5,
            'name':'babu',
            'place':'calicut',
            'mobile':7176541325,
            'email':'babu247@gmail.com',
            'joindate':'26/01/2017'
        },
        {
            'id':6,
            'name':'sajith',
            'place':'kochi',
            'mobile':8876542220,
            'email':'sajiths@gmail.com',
            'joindate':'23/09/2017'
        },
        {
            'id':7,
            'name':'sasi',
            'place':'calicut',
            'mobile':7776541322,
            'email':'sasip@gmail.com',
            'joindate':'06/10/2018'
        },
        {
            'id':8,
            'name':'raghu',
            'place':'trivandrum',
            'mobile':8776541321,
            'email':'anoop@gmail.com',
            'joindate':'06/10/2014'
        },
        {
            'id':9,
            'name':'yaseen',
            'place':'wayanad',
            'mobile':9776541324,
            'email':'yaseen34@gmail.com',
            'joindate':'06/11/2013'
        },{
            'id':10,
            'name':'yuvraj',
            'place':'calicut',
            'mobile':9666541382,
            'email':'yraj78@gmail.com',
            'joindate':'26/12/2012'
        }
    ]
    return students

